// ──────────────────────────────────────────────────────────
//  Shared priority model.
//  P0 = immediate life threat, P1 = emergent, P2 = urgent, P3 = routine.
// ──────────────────────────────────────────────────────────
import type { AssessmentResult, Priority } from "../types";
import { highestPriority } from "./util";

export const PRIORITY_META: Record<
  Priority,
  { label: string; action: string }
> = {
  P0: {
    label: "P0 — Immediate",
    action: "Call emergency services now. Possible life threat.",
  },
  P1: {
    label: "P1 — Emergent",
    action: "Seek emergency care immediately.",
  },
  P2: {
    label: "P2 — Urgent",
    action: "Get medical attention soon (urgent care / same day).",
  },
  P3: {
    label: "P3 — Routine",
    action: "Monitor; contact a clinician if symptoms worsen.",
  },
};

/** Combine several module results into one overall triage outcome. */
export function combineResults(results: AssessmentResult[]): {
  priority: Priority;
  worst: AssessmentResult | null;
} {
  if (!results.length) return { priority: "P3", worst: null };
  const priority = highestPriority(results.map((r) => r.priority));
  const rank: Record<Priority, number> = { P0: 0, P1: 1, P2: 2, P3: 3 };
  const worst = results.reduce((a, b) =>
    rank[a.priority] <= rank[b.priority] ? a : b,
  );
  return { priority, worst };
}

/** Plain-text EMS handoff packet from a set of results. */
export function emsPacket(results: AssessmentResult[]): string {
  const { priority } = combineResults(results);
  const lines: string[] = [];
  lines.push(`TRIAGE PRIORITY: ${PRIORITY_META[priority].label}`);
  lines.push(`Action: ${PRIORITY_META[priority].action}`);
  lines.push("");
  for (const r of results) {
    const flags = r.redFlags.filter((f) => f.detected);
    lines.push(
      `• ${r.module.toUpperCase()} — ${r.status} (${r.priority}, conf ${Math.round(
        r.confidence * 100,
      )}%)`,
    );
    for (const f of flags) {
      lines.push(
        `    ⚑ ${f.label} [${f.source}, ${Math.round(f.confidence * 100)}%]`,
      );
    }
  }
  lines.push("");
  lines.push("Generated by TriageLens — screening only, not a diagnosis.");
  return lines.join("\n");
}
